### ISSUE TITLE
Inform users of post-registration actions they must take

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chat.a8c.com#2]
After registration, there are mandatory steps users must take to secure their account. These steps are documented at https://matrixhandbook.wordpress.com/getting-started/first-steps

We need to find a way to send the above link to the user after registration, for example by:

- Having synapse send an email after registration
- Having a bot send a message after registration
- Other options

**Comment by psrpinto** [comment]
I've contacted EMS to see if they have suggestions about the best way to achieve this:

----

Hey folks,

I hope everything's good over there at Element HQ. We're looking into improving the experience for new users of the Automattic homeserver, and we thought you might have some tips for us.

Specifically, we would like to instruct our users of certain actions they must take after they register on the homeserver. We have an internal website with these instructions, and we'd like to send a link to said website to the user, after they've completed the registration flow.

We can think of a couple of ways we could do this:

1. Have synapse send an email to the user after registration
2. Have a bot send the user a message after registration

Do you know if any of these are possible, and do you have any ideas for other options?

Thanks very much in advance for any help!

**Comment by psrpinto** [comment]
EMS's suggestion was to edit Element's homepage, which is the solution we were trying to avoid, as per https://github.com/Automattic/Orbit/issues/183.

Since we don't have a proper way forward on this, and considering we can live without it, my suggestion would be to postpone it.

**Comment by akirk** [comment]
This is moot when we use SSO on Automattic, also Element does a better job now at communicating this.
